import { Injectable } from '@angular/core';

export interface Link16Message {
  id: number;
  type: string;
  data: string;
}

// Sample Data - hex generated by CoPilot
const MESSAGE_DATA: Link16Message[] = [
  { id: 1,  type: 'PPLI', data: '7a4c91f2' },
  { id: 2,  type: 'PPLI', data: '3e8b52d7' },
  { id: 3,  type: 'PPLI', data: 'c1f0a693' },
  { id: 4,  type: 'PPLI', data: '9b27e04f' },
  { id: 5,  type: 'PPLI', data: '54d8c2a1' },
  { id: 6,  type: 'PPLI', data: 'f6a3927c' },
  { id: 7,  type: 'PPLI', data: '28e4b5d9' },
  { id: 8,  type: 'PPLI', data: '83c7fa10' },
  { id: 9,  type: 'PPLI', data: 'da19b46e' },
  { id: 10, type: 'PPLI', data: '41f2c8a7' },
  { id: 11, type: 'PPLI', data: 'b7e05d34' },
  { id: 12, type: 'PPLI', data: '6c9a83f1' },
  { id: 13, type: 'PPLI', data: '2fd4819b' },
  { id: 14, type: 'PPLI', data: 'e0a572c6' },
  { id: 15, type: 'PPLI', data: '95c3d84a' },
  { id: 16, type: 'PPLI', data: '7bef20d1' },
  { id: 17, type: 'PPLI', data: '3a9c5f82' },
  { id: 18, type: 'PPLI', data: 'c8d4710e' },
  { id: 19, type: 'PPLI', data: 'f1b62a93' },
  { id: 20, type: 'PPLI', data: '4e7d9c50' },
  { id: 21, type: 'PPLI', data: 'a2c8f134' },
  { id: 22, type: 'PPLI', data: '59e0b7d8' },
  { id: 23, type: 'PPLI', data: 'd3a4916f' },
  { id: 24, type: 'PPLI', data: '86f2c0a9' },
  { id: 25, type: 'PPLI', data: '1b7e4d23' },
  { id: 26, type: 'PPLI', data: 'fa3095c7' },
  { id: 27, type: 'PPLI', data: '62c8e1b4' },
  { id: 28, type: 'PPLI', data: '9ed4a072' },
  { id: 29, type: 'PPLI', data: '35f8c1d9' },
  { id: 30, type: 'PPLI', data: 'c7a03e58' },
];

@Injectable({
  providedIn: 'root',
})
export class Link16Service {
  constructor() { }
  displayedColumns: string[] = ['id', 'type', 'data'];
  dataSource = MESSAGE_DATA;
}
